# Generated by Django 2.1.4 on 2019-01-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceleration',
            old_name='x_axis',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='acceleration',
            old_name='y_axis',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='acceleration',
            old_name='z_axis',
            new_name='z',
        ),
    ]
