# Generated by Django 2.1.4 on 2019-01-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_health', '0002_auto_20190102_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_health.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='EnvSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.FloatField(default=0.0)),
                ('m_peak_power', models.FloatField(default=0.0)),
                ('m_average_power', models.FloatField(default=0.0)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_health.DataSource')),
            ],
        ),
    ]
